//
// Created by crypt on 1/7/2017.
//

#ifndef VULKANWORKSHOP_VERTEXBUFFERMANAGER_H
#define VULKANWORKSHOP_VERTEXBUFFERMANAGER_H


class VertexBufferManager {
    
};


#endif //VULKANWORKSHOP_VERTEXBUFFERMANAGER_H
